---
acme_email: ''
acme_server: https://acme-staging-v02.api.letsencrypt.org/directory
acme_agreement_url: https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf
configure_zabbix_agent: false
